### ISSUE TITLE
lookup hardware profiles by hardwarename

### ISSUE THREAD

**Issue by justadreamer** [51Degrees/ua-parser-js#2]
Hi all

I had a client request to implement an app that would lookup hardware profiles (that would contain `price` and `release` date as properties) based on one of the following inputs:
a) `hardwarename` 
b) a combination of `hardwarevendor` + `hardwaremodel` 
c) a combination of `hardwarevendor` + `hardwarename` 

There are 2 cases:
1. `hardwarevendor` + `hardwaremodel`/`hardwarename` is detected from the incoming request / browser environment on the device itself
2. `hardwarename` (or other combinations) are input directly by the user.

UAParser can help to detect the `hardwarevendor` + `hardwaremodel` + `hardwarename` + `price` + `release` on the current device, but it is incapable to lookup hardware profiles based on the user input of say `hardwarename`. 

I saw an example in the [device-detection-node](https://github.com/51Degrees/device-detection-node): https://github.com/51Degrees/device-detection-node/blob/master/fiftyone.devicedetection.cloud/examples/cloud/nativemodellookup-console/nativeModelLookup.js  - it allows to do a lookup based on `nativemodel`, however trying to use `query.hardwarename` instead does not yield results.  

I also tried to use [cloud.51degrees.com](https://cloud.51degrees.com/api-docs/index.html) API directly providing it `hardwarename` as evidence parameter in the get request - similarly it does not yield results.  Seems that only `nativemodel` is supported but not `hardwarename` lookups.  Is there a way or a workaround in some of 51degrees products to implement hardware profile lookups by the input combinations above? 

Thanks.

**Comment by Sara51D** [comment]
Thank you for posting this issue. The solution to this issue is the .csv data file available as part of the 51Degrees 'Biggest' subscription. Please see [51Degrees Price Plans](https://51degrees.com/pricing)
Details of the .csv file are available [here](https://51degrees.com/documentation/4.4/_device_detection__features__csv_data_file.html)
This file includes all property values for all profiles (hardware, platform, browser, and crawler). This data may be used to lookup details using various keys such as TAC or the model name returned by native apps running on the device.
